<?php if (! defined('HARMONY_INCLUDE')) die("Harmony Library is not loaded !");
/**\defgroup database Database access
 *
 * Database module for Harmony PHP Library
 *  
 * Author: FredTGZ
 *  
 * Description:
 * This module implements database access and querying.
 *  
 * Howto:  
 */
 	global $loadmodule;
	
	if ($loadmodule !== false) {
		require_once("ckeditor.inc");
	}
	else require("module.nfo");
?>
