CREATE TABLE {DB_PREFIX}_USERS (
	USER_ID			VARCHAR(30) PRIMARY KEY,
	USER_NAME		VARCHAR(100) NULL,
	USER_SURNAME	VARCHAR(100) NULL,
	USER_PASSWORD	VARCHAR(50) NOT NULL,
	USER_EMAIL		VARCHAR(100) NOT NULL,
	USER_LASTLOGIN	DATETIME NULL,

	USER_LANGUAGE	VARCHAR(100) NULL,
	USER_BIRTHDATE	DATETIME NULL,
	USER_ICQ		VARCHAR(100) NULL,
	USER_AIM		VARCHAR(100) NULL,
	USER_MSN		VARCHAR(100) NULL,
	USER_AIM		VARCHAR(100) NULL,
	USER_YAHOO_MSN	VARCHAR(100) NULL,
	USER_WEB_SITE	VARCHAR(100) NULL,
	USER_SIGNATURE	VARCHAR(255) NULL,
	USER_JOB		VARCHAR(100) NULL,
	USER_LEASURE	VARCHAR(100) NULL
)

INSERT INTO {DB_PREFIX}_RIGHTS(USER_ID, USER_NICKNAME, USER_PASSWORD, USER_EMAIL)
VALUES('admin', 'Administrator', PASSWORD('admin'), 'root@localhost')
